# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-21 06:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-id', '-Timestamp', '-Updated']},
        ),
        migrations.AddField(
            model_name='post',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
