# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-23 10:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='Publish',
            field=models.DateField(auto_now=True, default=datetime.datetime(2017, 5, 23, 10, 12, 49, 820585, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
